#!/bin/bash

echo "Music XML parsing tests"

echo "Phase 1 : parsing"
for a in $*
do 
	echo "parsing $a" 
	./ReadWrite $a > $a.copy
done

echo ""
echo "Phase 2 : diffing"
for a in $*
do
	echo "Diffing $a and $a.copy:"
	diff -b -B $a $a.copy >$a.diff
done

